// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgu8KGGXGf8gpN4ZEJzEfFPEQAF1wou10',
    appId: '1:142862392331:web:e5c101b5196b01e4f67b0e',
    messagingSenderId: '142862392331',
    projectId: 'fluttergps-d78d5',
    authDomain: 'fluttergps-d78d5.firebaseapp.com',
    databaseURL: 'https://fluttergps-d78d5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fluttergps-d78d5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjn-GxEmvPteRNkLTBlyXT0aHXeS7bQL0',
    appId: '1:142862392331:android:a7ceec375680e1a1f67b0e',
    messagingSenderId: '142862392331',
    projectId: 'fluttergps-d78d5',
    databaseURL: 'https://fluttergps-d78d5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fluttergps-d78d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6t9GUdWob20Wskw7DPQSyaUY2VAImn5w',
    appId: '1:142862392331:ios:fba8f0e3dbba9f3df67b0e',
    messagingSenderId: '142862392331',
    projectId: 'fluttergps-d78d5',
    databaseURL: 'https://fluttergps-d78d5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fluttergps-d78d5.appspot.com',
    iosClientId: '142862392331-o3hs0m8kktu6m45d6aoklqn368dqogf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.tanderjelek3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6t9GUdWob20Wskw7DPQSyaUY2VAImn5w',
    appId: '1:142862392331:ios:fba8f0e3dbba9f3df67b0e',
    messagingSenderId: '142862392331',
    projectId: 'fluttergps-d78d5',
    databaseURL: 'https://fluttergps-d78d5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fluttergps-d78d5.appspot.com',
    iosClientId: '142862392331-o3hs0m8kktu6m45d6aoklqn368dqogf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.tanderjelek3',
  );
}
